### ISSUE TITLE
Unable to open /tmp/tscan20152_iso_cm.tab for reading.  Aborting program.

### ISSUE THREAD

**Issue by asttra** [UCSC-LoweLab/tRNAscan-SE#2]
I get an error about tmp files when I try to run the program.

**Comment by patriciaplchan** [comment]
Please check to make sure that you have unused disk space in /tmp on the system you are running tRNAscan-SE. If there is extra space but you are getting the error, it is possible that one or more of your input sequences do not have any results. I will need to know the options you use when running tRNAscan-SE and possibly a copy of the input sequences in order to reproduce the problem and identify a solution.

**Comment by chipotlau** [comment]
Hello, 

I am getting the same error. I edited the temporary directory PATH in the tRNAscan-SE.conf file, but when I run tRNAscan-SE, it still uses the default "/tmp" directory. How can I change the temporary directory that the program uses?

Many thanks!

**Comment by patriciaplchan** [comment]
Hi Emily,

It looks like that tRNAscan-SE is not using the copy of tRNAscan-SE.conf you have updated. Please check to make sure that the value in the tRNAscan-SE.conf you changed is for the field "temp_dir". Then look inside the installed version of tRNAscan-SE executable to confirm the value in the statement starting with "our $default_conf = " is the same path as where tRNAscan-SE.conf that has the updated temp_dir is located. If it is not, you may not have set the prefix path appropriately when running configure before make. If you do not want to rebuild and reinstall the software, you can use the option -c to specify the use of your updated tRNAscan-SE.conf.

**Comment by chipotlau** [comment]
Hi, 

Many thanks for your suggestion. It seems like my /tmp directory has plenty of space, so that is not the issue. I think one of my input sequences may not have a result- I am using the command tRNAscan-SE -o outputfile.out --thread 14 genome_softmasked.fa

Do you have any suggestions? Thanks for your time!

**Comment by patriciaplchan** [comment]
Hi Emily,

I think the issue occurs when one of your sequences has a very low scoring hit from the domain-specific search with a below-cutoff-score at the isotype-specific search. This is a very rare case from our experience although it may still occur. We will try to handle the situation better in the next release. Meanwhile, you can add "-S off" in your command to bypass the isotype-specific search and the error should not occur. The caveat is that bypassing the isotype-specific search will disable the distinction between tRNA for initiator Met and elongator Met, making all of them having isotype as Met.
