### ISSUE TITLE
Sup isotype

### ISSUE THREAD

**Issue by jucosie** [UCSC-LoweLab/tRNAscan-SE#35]
Hi,

First off, big thanks for creating such a fantastic tool! I've been tinkering around with the tncRNA-toolkit, which relies on your program for tRNA gene detection. I have found out that your program uses an isotype called tRNA-Sup that I haven't been able to identify. Mind shedding some light on it?

Best

**Comment by patriciaplchan** [comment]
tRNA-Sup stands for suppressor tRNAs. They carry anticodons that base pair with stop codons. Because suppressor tRNAs don't usually exist in nature, those that are detected in genomic sequences tend to be low-scoring pseudogenes.

If you are using tncRNA toolkit, you may also want to check out [tRAX] (http://trna.ucsc.edu/tRAX/) and [tDRnamer] (http://trna.ucsc.edu/tDRnamer/) developed by our lab. tRAX is a complete pipeline for tRNA and tRNA-derived small RNA sequencing data analysis. tDRnamer provides standard naming convention and annotations to tRNA-derived RNAs.

**Comment by jucosie** [comment]
Perfect, thank you very much for the quick response!
